version: '3.1'

services:

  # Biotransformer Webservices
  cts-biotransformer:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/quanted/cts-biotransformer:dev-kube
    container_name: cts-biotransformer
    ports:
      - "5002:5002"
    # volumes:
    #   - ./:/src
    environment:
      - BT_JAR_PATH=/src/biotransformer3.0jar
      - BT_JAR_NAME=biotransformer.jar  # name of .jar in biotransformer3.0jar/
